version: "3.9"
services:
  workerdisk:
    build: .
    environment:
      - APP_ID=${APP_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN} 
      - CHANNEL=${CHANNEL}
      - OWNER_ID=${OWNER_ID}
      - AUTH_CHANNEL=${AUTH_CHANNEL}
      - DATABASE_URI=${DATABASE_URI}
      - LOG_CHANNEL=${LOG_CHANNEL}
